=== Morabotti/route-management/src/main/resources/dataset.dtd
<!ELEMENT dataset (
        person*,
        location*,
        primary_location*,
        vehicle*,
        step*,
        route*,
        step_item*
)>

<!ELEMENT person EMPTY>
<!ATTLIST person
        id CDATA #REQUIRED
        name CDATA #REQUIRED
        deleted_at CDATA #IMPLIED
>

<!ELEMENT location EMPTY>
<!ATTLIST location
        id CDATA #REQUIRED
        address CDATA #REQUIRED
        zip CDATA #REQUIRED
        city CDATA #REQUIRED
        latitude CDATA #REQUIRED
        longitude CDATA #REQUIRED
        deleted_at CDATA #IMPLIED
>

<!ELEMENT primary_location EMPTY>
<!ATTLIST primary_location
        id CDATA #REQUIRED
        person_id CDATA #REQUIRED
        location_id CDATA #REQUIRED
>

<!ELEMENT vehicle EMPTY>
<!ATTLIST vehicle
        id CDATA #REQUIRED
        license_number CDATA #REQUIRED
        deleted_at CDATA #IMPLIED
>

<!ELEMENT route EMPTY>
<!ATTLIST route
        id CDATA #REQUIRED
        vehicle_id CDATA #REQUIRED
        destination_id CDATA #REQUIRED
        start_time CDATA #IMPLIED
        deleted_at CDATA #IMPLIED
>

<!ELEMENT step EMPTY>
<!ATTLIST step
        id CDATA #REQUIRED
        route_id CDATA #REQUIRED
        location_id CDATA #REQUIRED
        priority CDATA #IMPLIED
        deleted_at CDATA #IMPLIED
>

<!ELEMENT step_item EMPTY>
<!ATTLIST step_item
        id CDATA #REQUIRED
        step_id CDATA #REQUIRED
        person_id CDATA #REQUIRED
        deleted_at CDATA #IMPLIED
>

=== Morabotti/route-management/src/main/resources/dataset.xml
<!DOCTYPE dataset SYSTEM "dataset.dtd">
<dataset>
  <person id="1" name="Test Person" />
  <person id="2" name="Example Molly" />

  <location
    id="1"
    address="teststreet 2"
    zip="65200"
    city="Vaasa"
    latitude="63.1092301"
    longitude="21.6019174"
  />
  <location
    id="2"
    address="teststreet 3"
    zip="65200"
    city="Vaasa"
    latitude="63.2092301"
    longitude="21.7019174"
  />
  <location
    id="3"
    address="teststreet 5"
    zip="65200"
    city="Vaasa"
    latitude="63.3092301"
    longitude="21.8019174"
  />

  <vehicle id="1" license_number="ABC-123" />

  <primary_location id="1" person_id="1" location_id="1" />
  <primary_location id="2" person_id="1" location_id="3" />
  <primary_location id="3" person_id="2" location_id="2" />

  <route id="1" vehicle_id="1" destination_id="3" />

  <step id="1" route_id="1" location_id="2" priority="1" />
  <step id="2" route_id="1" location_id="1" priority="2" />

  <step_item id="1" step_id="1" person_id="1" />
  <step_item id="2" step_id="2" person_id="2" />
</dataset>
